# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='name')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='keywords')),
                ('is_public', models.BooleanField(verbose_name='is public')),
                ('model', models.TextField(blank=True, null=True, verbose_name='model')),
                ('hits', models.IntegerField(default=0, verbose_name='hits')),
                ('stars', models.FloatField(default=0, verbose_name='stars')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='RelationInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Behaviors',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Equations',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Influences',
            fields=[
                ('model', models.TextField(blank=True, null=True, verbose_name='model')),
                ('concepts', models.IntegerField(default=0, verbose_name='concepts')),
                ('cycles', models.IntegerField(default=0, verbose_name='cycles')),
                ('clones', models.IntegerField(default=0, verbose_name='clones')),
                ('material', models.IntegerField(default=0, verbose_name='material')),
                ('information', models.IntegerField(default=0, verbose_name='information')),
                ('sector', models.IntegerField(default=0, verbose_name='sector')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Prose',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='prose title')),
                ('description', models.TextField(max_length=2000, verbose_name='prose description')),
                ('keywords', models.CharField(max_length=200, verbose_name='prose keywords')),
                ('model', models.TextField(blank=True, null=True, verbose_name='model')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StockAndFlow',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='base_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
