# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.EvoUser'),
        ),
        migrations.CreateModel(
            name='ElementSaf',
            fields=[
                ('influences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.StockAndFlow')),
            ],
        ),
        migrations.CreateModel(
            name='RelationSaf',
            fields=[
                ('stock_and_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.StockAndFlow')),
            ],
        ),
        migrations.CreateModel(
            name='SectorInf',
            fields=[
                ('influences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Influences')),
            ],
        ),
        migrations.CreateModel(
            name='SectorSaf',
            fields=[
                ('stock_and_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.StockAndFlow')),
            ],
        ),
        migrations.AddField(
            model_name='relationinf',
            name='influences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Influences'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AddField(
            model_name='elementinf',
            name='influences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Influences'),
        ),
    ]
